title: FHIL SOPs
description: Standard operating procedures for the Fred Hutch Innovation Lab
theme: just-the-docs

url: https://Fred-Hutch-Innovation-Lab.github.io/SOPs

aux_links:
  Source repo: https://github.com/Fred-Hutch-Innovation-Lab/SOPs
