title: FHIL SOPs
description: Standard operating procedures for the Fred Hutch Innovation Lab
theme: just-the-docs

url: https://FHIL-SOPs.github.io

aux_links:
  Template Repository: https://github.com/Fred-Hutch-Innovation-Lab/SOPs
